STONES = [
    {
        'shape': 'Круг',
        'carat': 1.05,
        'color': 'G',
        'clarity': 'VVS1',
        'score': 95,
        'price': 32200,
        'priceText': '32 200',
        'diameter': 6.5,
        'meta': '6.5 мм · ex ex vg · none',
        'weight': '1–1.49',
        'scoreBand': '95–98',
        'fluor': 'None',
        'finish': '2Ex/1VG+',
        'section': 'main',
        'report': 'IGI LG000001',
        'tags': '<span class=tag>О</span><span class="tag blue">Б</span>',
    },
    {
        'shape': 'Круг',
        'carat': 1.51,
        'color': 'E',
        'clarity': 'VS1',
        'score': 86,
        'price': 58500,
        'priceText': '58 500',
        'diameter': 7.4,
        'meta': '7.4 мм · ex ex vg · none',
        'weight': '1.5–1.99',
        'scoreBand': '80–89',
        'fluor': 'None',
        'finish': '2Ex/1VG+',
        'section': 'main',
        'report': 'IGI LG000002',
        'tags': '<span class="tag gray">К</span><span class=tag>О</span>',
    },
    {
        'shape': 'Круг',
        'carat': 1.00,
        'color': 'F',
        'clarity': 'VS2',
        'score': 77,
        'price': 34900,
        'priceText': '34 900',
        'diameter': 6.4,
        'meta': '6.4 мм · ex ex vg · none',
        'weight': '1–1.49',
        'scoreBand': '50–79',
        'fluor': 'None',
        'finish': '2Ex/1VG+',
        'section': 'main',
        'report': 'IGI LG000003',
        'tags': '<span class=tag>БАЛАНС</span>',
    },
    {
        'shape': 'Круг',
        'carat': 1.22,
        'color': 'D',
        'clarity': 'VVS2',
        'score': 92,
        'price': 41800,
        'priceText': '41 800',
        'diameter': 6.9,
        'meta': '6.9 мм · ex ex ex · none',
        'weight': '1–1.49',
        'scoreBand': '90–94.9',
        'fluor': 'None',
        'finish': 'Ex/Ex/Ex+',
        'section': 'main',
        'report': 'IGI LG000004',
        'tags': '<span class="tag blue">Б</span><span class=tag>О</span>',
    },
    {
        'shape': 'Круг',
        'carat': 1.74,
        'color': 'F',
        'clarity': 'VS1',
        'score': 89,
        'price': 67900,
        'priceText': '67 900',
        'diameter': 7.8,
        'meta': '7.8 мм · ex ex vg · faint',
        'weight': '1.5–1.99',
        'scoreBand': '80–89',
        'fluor': 'Faint',
        'finish': '2Ex/1VG+',
        'section': 'main',
        'report': 'IGI LG000005',
        'tags': '<span class="tag gray">К</span><span class="tag blue">Б</span>',
    },
    {
        'shape': 'Круг',
        'carat': 2.03,
        'color': 'G',
        'clarity': 'VS2',
        'score': 84,
        'price': 88400,
        'priceText': '88 400',
        'diameter': 8.1,
        'meta': '8.1 мм · ex vg vg · none',
        'weight': '2–2.49',
        'scoreBand': '80–89',
        'fluor': 'None',
        'finish': '2Ex/1VG+',
        'section': 'main',
        'report': 'IGI LG000006',
        'tags': '<span class=tag>БАЛАНС</span>',
    },
    {
        'shape': 'Круг',
        'carat': 2.41,
        'color': 'E',
        'clarity': 'VVS1',
        'score': 99,
        'price': 126300,
        'priceText': '126 300',
        'diameter': 8.7,
        'meta': '8.7 мм · ex ex ex · none',
        'weight': '2–2.49',
        'scoreBand': '99+',
        'fluor': 'None',
        'finish': 'Ex/Ex/Ex+',
        'section': 'main',
        'report': 'IGI LG000007',
        'tags': '<span class=tag>О</span><span class="tag blue">Б</span>',
    },
]
