from __future__ import annotations


# TODO: Move index JS handlers to safer structured script module after MVP smoke.
SHARE_CLICK = "let url;try{url=new URL(window.parent.location.href);}catch(e){url=new URL(window.location.href);}url.searchParams.set('page','tools');url.searchParams.set('tool','kurgin_index');url.hash='kurgin-index';const shareData={title:'KURGIN Index',text:'KURGIN Index — ориентир для сопоставления лабораторных бриллиантов',url:url.toString()};if(navigator.share){navigator.share(shareData).catch(()=>{});}else if(navigator.clipboard){navigator.clipboard.writeText(url.toString()).then(()=>{this.textContent='Ссылка скопирована';setTimeout(()=>{this.textContent='↗ Поделиться Index';},1400);}).catch(()=>{window.prompt('Скопируйте ссылку',url.toString());});}else{window.prompt('Скопируйте ссылку',url.toString());}"

DEEP_LINK_INIT = "const trigger=this;setTimeout(()=>{const allowed=['single_stone_analyzer','kurgin_index','database_analysis','excel_analyzer','kurgin_academy'];try{const url=new URL(window.parent.location.href);const tool=url.searchParams.get('tool');if(!allowed.includes(tool))return;const root=trigger.closest('.tools-page');const tab=root&&root.querySelector('[data-tool-tab=\\\"'+tool+'\\\"]');if(tab){tab.click();}if(url.hash){const target=root&&root.querySelector(url.hash);if(target)target.scrollIntoView({block:'start'});}}catch(e){}},0);"

SCORE_RANGE_CLICK = "const shell=this.closest('.index-shell');const card=this.closest('.index-score-card');card.querySelectorAll('[data-score-range]').forEach(b=>b.setAttribute('aria-selected','false'));this.setAttribute('aria-selected','true');const label=this.getAttribute('data-score-label');const ru=this.getAttribute('data-score-ru');const range=this.getAttribute('data-score-range-label');const mode=this.getAttribute('data-score-mode');const coeff=Number(this.getAttribute('data-score-coefficient')||0);const coeffLabel=this.getAttribute('data-score-coefficient-label');const selectedText=label+' / '+ru+' · '+range;card.querySelectorAll('.index-score-selected').forEach(el=>el.textContent=selectedText);shell.querySelectorAll('.index-range-summary-selected').forEach(el=>el.textContent=selectedText);shell.querySelectorAll('.index-score-coefficient,.index-range-summary-coefficient').forEach(el=>el.textContent='Коэффициент: '+coeffLabel);shell.querySelectorAll('.index-cell').forEach(cell=>{const base=Number(cell.getAttribute('data-index-base')||0);const main=cell.querySelector('.index-cell-main');const sub=cell.querySelector('.index-cell-sub');if(!base){main.textContent='request';main.classList.add('muted');sub.textContent='—';return;}if(mode==='numeric'){main.textContent=String(Math.round(base*coeff))+' $/ct';main.classList.remove('muted');sub.textContent=coeffLabel;}else{main.textContent='request';main.classList.add('muted');sub.textContent=mode==='request_caution'?'caution':'—';}});"

INDEX_PDF_PRINT = "const template=document.getElementById('index-pdf-template');if(!template){window.print();return;}const win=window.open('', '_blank');if(!win){window.print();return;}win.document.open();win.document.write('<!doctype html><html><head><meta charset=\\\"utf-8\\\"><title>KURGIN Index PDF</title><style>body{font-family:Arial,sans-serif;color:#111;margin:28px}.pdf-head{display:flex;align-items:center;gap:16px;border-bottom:1px solid #111;padding-bottom:16px;margin-bottom:18px}.pdf-logo{width:84px;height:auto}.pdf-title{font-size:22px;font-weight:700;letter-spacing:.04em}.pdf-meta{font-size:12px;color:#555;margin-top:4px}.pdf-note{font-size:11px;line-height:1.45;border:1px solid #ddd;padding:10px;margin:14px 0}.pdf-section{break-inside:avoid;margin:16px 0}.pdf-section h2{font-size:16px;margin:0 0 8px}.pdf-table{width:100%;border-collapse:collapse;font-size:10px}.pdf-table th,.pdf-table td{border:1px solid #999;padding:5px;text-align:center}.pdf-table th{background:#eee}.pdf-table tbody th{text-align:left;background:#f7f7f7}@media print{body{margin:18mm}.pdf-section{page-break-inside:avoid}}</style></head><body>'+template.innerHTML+'</body></html>');win.document.close();setTimeout(()=>{win.focus();win.print();},250);"

INDEX_VIEW_TOGGLE = "const shell=this.closest('.index-shell');const panel=shell&&shell.querySelector('.index-view-panel');if(!panel)return;const shouldOpen=panel.hidden;panel.hidden=!shouldOpen;this.setAttribute('aria-expanded',String(shouldOpen));if(shouldOpen)panel.scrollIntoView({block:'nearest'});"

INDEX_EXPAND_ALL_COLORS = "const shell=this.closest('.index-shell');shell.querySelectorAll('.index-color-section').forEach(section=>{section.open=true;});"

INDEX_COLLAPSE_ALL_COLORS = "const shell=this.closest('.index-shell');shell.querySelectorAll('.index-color-section').forEach(section=>{section.open=false;});"
